title: GAVE-frontend
description: "August 2023 to June 2024"
owner_name: Aliya Tang
github_username: aliyatang
github_repo: "GAVE-frontend"
repository: "aliyatang/GAVE-frontend"
baseurl: "/GAVE-frontend"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/GAVE-frontend"}
    - { platform: github, user_url: "https://github.com/GAVE-CSA"}
    - { platform: github, user_url: "https://github.com/h4seeb-cmd"} 
plugins:
- jekyll-remote-theme
future: true
